[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Enable Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables are set in Netlify dashboard 